version: '3.8'

services:
  pm_web:
    build: .
    container_name: pm_web
    restart: always
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - pm_db
    ports:
      - "8090:8000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

  pb_bot:
    build: .
    container_name: pb_bot
    restart: always
    depends_on:
      - pm_db
    env_file:
      - .env
    command: ["python", "manage.py", "app"]

  pm_db:
    image: postgres:16-alpine
    container_name: pm_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5566:5432"

volumes:
  postgres_data: